name: 'Setup git lfs'

runs:
  using: "composite"
  steps:
    # original: https://github.com/actions/checkout/issues/165#issuecomment-657673315
    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      shell: bash

    - name: Restore LFS cache
      uses: actions/cache@v4
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

    - name: Git LFS Pull
      run: git lfs pull
      shell: bash
