name: 'Setup JDK'

runs:
  using: "composite"
  steps:
  - name: Copy CI gradle.properties
    run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
    shell: bash

  - name: Set up JDK
    uses: actions/setup-java@v4
    with:
      distribution: 'zulu'
      java-version: '21'

  # Better than caching and/or extensions of actions/setup-java
  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v3
    with:
      gradle-version: wrapper
