name: ComposePreviewTest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          lfs: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run build
        run: ./gradlew validateDebugScreenshotTest
      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: my-artifact
          path: app/build/reports/screenshotTest
          retention-days: 7
