name: ComposePreviewTest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          lfs: false

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version: 17

      # Better than caching and/or extensions of actions/setup-java
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-cleanup: always

      - name: Run Compose Preview Screenshot Tests
        run: ./gradlew validateDebugScreenshotTest

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: compose preview screenshot test outputs
          path: |
            **/build/reports/screenshotTest
          retention-days: 7
