name: RoborazziTestStore

on:
  push:
    branches:
      - main
  pull_request:

permissions: { }

jobs:
  store-screenshot-test:
    runs-on:
      group: mad-ci-ubuntu-22.04
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          lfs: false

      - uses: ./.github/actions/setup-lfs

      - uses: ./.github/actions/setup-java

      - name: record screenshot
        id: record-test
        run: |
          # Use --rerun-tasks to disable cache for test task
          ./gradlew recordRoborazziDebug --rerun-tasks -Pscreenshot

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 7

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-reports
          path: |
            **/build/reports
          retention-days: 7

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-test-results
          path: |
            **/build/test-results
          retention-days: 7
