name: RoborazziTestCompare

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  compare-screenshot-test:
    runs-on:
      group: mad-ci-ubuntu-22.04
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          lfs: false

      - uses: ./.github/actions/setup-lfs

      - uses: ./.github/actions/setup-java

      - uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: screenshot
          workflow: roborazzi-test-store.yml
          branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.repository.default_branch }}

      - name: compare screenshot test
        id: compare-screenshot-test
        run: |
          ./gradlew compareRoborazziDebug -Pscreenshot

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff-and-reports
          path: |
            **/build/outputs/roborazzi
            **/build/reports
          retention-days: 7

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff-test-results
          path: |
            **/build/test-results
          retention-days: 7

      - name: Save PR number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
